spring:
  application:
    名字: adg-rule
  profiles:
    已激活: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  rule:
    #远程规则
    remote:
      - 'https://filters.adtidy.org/android/filters/15_optimized.txt'
      - 'https://filters.adtidy.org/android/filters/101_optimized.txt'
      - 'https://filters.adtidy.org/android/filters/104_optimized.txt'
      - 'https://filters.adtidy.org/android/filters/208_optimized.txt'
      - 'https://filters.adtidy.org/android/filters/242_optimized.txt'
      - 'https://filters.adtidy.org/android/filters/11_optimized.txt'
      - 'https://filters.adtidy.org/android/filters/14_optimized.txt'
      - 'https://filters.adtidy.org/android/filters/18_optimized.txt'
      - 'https://filters.adtidy.org/android/filters/19_optimized.txt'
      - 'https://filters.adtidy.org/android/filters/20_optimized.txt'
      - 'https://filters.adtidy.org/android/filters/21_optimized.txt'
      - 'https://filters.adtidy.org/android/filters/224_optimized.txt'
      - 'https://filters.adtidy.org/android/filters/22_optimized.txt'
      - 'https://filters.adtidy.org/android/filters/2_optimized.txt'
      - 'https://filters.adtidy.org/android/filters/4_optimized.txt'
      - 'https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/rule.txt' #name: 乘风 广告过滤规则
      - 'https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/mv.txt' #name: 乘风 视频过滤规则
      - 'https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts' #name: 大圣净化（针对国内视频）
      - 'https://raw.githubusercontent.com/mrchi/adaway-hosts/main/anti-ad-adaway.txt'
    #本地规则
    local: #本地规则请将文件移动到项目路径rule目录中
      - 'mylist.txt'
  output:
    path: rule   #规则文件输出路径，相对路径默认从 项目目录开始
    files:
      all.txt:    #输出文件名
        - DOMAIN  #域名规则，仅完整域名
        - REGEX   #正则规则，包含正则的域名规则，AdGH支持
        - MODIFY  #修饰规则，添加了一些修饰符号的规则，AdG支持
        - HOSTS   #Hosts规则
      adgh.txt:
        - DOMAIN
        - REGEX
#        - HOSTS
      hosts.txt:
        - HOSTS
      regex.txt:
        - REGEX
      domain.txt:
        - DOMAIN
      modify.txt:
        - MODIFY
